import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    category: "Medicamentos",
    price: 3500,
    stock: 120,
    stockStatus: "Disponible",
    description: "Analgésico y antipirético. Caja x 20 tabletas.",
    brand: "Genfar",
  },
  {
    id: 2,
    name: "Ibuprofeno 400mg",
    category: "Medicamentos",
    price: 4200,
    stock: 85,
    stockStatus: "Disponible",
    description: "Antiinflamatorio no esteroide. Caja x 20 tabletas.",
    brand: "MK",
  },
  {
    id: 3,
    name: "Loratadina 10mg",
    category: "Medicamentos",
    price: 5800,
    stock: 8,
    stockStatus: "Stock Bajo",
    description: "Antihistamínico para alergias. Caja x 10 tabletas.",
    brand: "Genfar",
  },
  {
    id: 4,
    name: "Omeprazol 20mg",
    category: "Medicamentos",
    price: 6500,
    stock: 0,
    stockStatus: "Agotado",
    description: "Inhibidor de la bomba de protones. Caja x 14 cápsulas.",
    brand: "Bayer",
  },
  {
    id: 5,
    name: "Vitamina C 500mg",
    category: "Vitaminas",
    price: 12000,
    stock: 45,
    stockStatus: "Disponible",
    description: "Refuerza el sistema inmunológico. Frasco x 30 tabletas.",
    brand: "Naturell",
  },
  {
    id: 6,
    name: "Vitamina D3 1000 UI",
    category: "Vitaminas",
    price: 18500,
    stock: 30,
    stockStatus: "Disponible",
    description: "Esencial para huesos y sistema inmune. Frasco x 60 cápsulas.",
    brand: "Naturell",
  },
  {
    id: 7,
    name: "Complejo B",
    category: "Vitaminas",
    price: 9800,
    stock: 5,
    stockStatus: "Stock Bajo",
    description: "Vitaminas del grupo B para la energía. Frasco x 30 tabletas.",
    brand: "MK",
  },
  {
    id: 8,
    name: "Shampoo Anticaspa",
    category: "Higiene Personal",
    price: 22000,
    stock: 60,
    stockStatus: "Disponible",
    description: "Control de caspa y cuero cabelludo graso. 375ml.",
    brand: "Head & Shoulders",
  },
  {
    id: 9,
    name: "Gel Antibacterial 500ml",
    category: "Higiene Personal",
    price: 8500,
    stock: 200,
    stockStatus: "Disponible",
    description: "Elimina el 99.9% de gérmenes. Sin enjuague.",
    brand: "Antibac",
  },
  {
    id: 10,
    name: "Protector Solar SPF 50",
    category: "Cuidado de la Piel",
    price: 35000,
    stock: 25,
    stockStatus: "Disponible",
    description: "Protección UVA/UVB de amplio espectro. 100ml.",
    brand: "Isdin",
  },
  {
    id: 11,
    name: "Crema Hidratante",
    category: "Cuidado de la Piel",
    price: 28000,
    stock: 3,
    stockStatus: "Stock Bajo",
    description: "Hidratación profunda para pieles secas. 200ml.",
    brand: "Eucerin",
  },
  {
    id: 12,
    name: "Pañales Talla M",
    category: "Bebés",
    price: 45000,
    stock: 40,
    stockStatus: "Disponible",
    description: "Pañales ultraabsorbentes con protección activa. Paquete x 30.",
    brand: "Pampers",
  },
];

export const categories = [
  "Todas",
  "Medicamentos",
  "Vitaminas",
  "Higiene Personal",
  "Cuidado de la Piel",
  "Bebés",
] as const;
